name: JoinMessage
main: jp.mydns.toraden.joinmessage.Main
version: 0.1
author: toradencom
description: JoinMessage
commands:
  2020vote:
  vote:
    description: show toraden.com JMS vote link